---
name: CreateNameTag
author: Runa_Ja
version: 2.1
api: 3.0.0
main: CONSOLE\CreateNameTag\Main
commands:
  title:
    description: SetNameTagCommand
permissions:
 title:
  default: true
  description: "Allows using all the ip things"
  children:
   title.command:
    default: true
    description: "Allows using all the ip commands"