---
name: CreateNameTag
author: Shigure
version: 2.8
api: 3.0.0
main: CONSOLE\CreateNameTag\Main
commands:
  title:
    description: Original your title
permissions:
 title:
  default: true
  description: "Allows using all the ip things"
  children:
   title.command:
    default: true
    description: "Allows using all the ip commands"