---
#.------..------..------..------..------..------.
#|C.--. ||O.--. ||N.--. ||F.--. ||I.--. ||G.--. |
#| :/\: || :/\: || :(): || :(): || (\/) || :/\: |
#| :\/: || :\/: || ()() || ()() || :\/: || :\/: |
#| '--'C|| '--'O|| '--'N|| '--'F|| '--'I|| '--'G|
#`------'`------'`------'`------'`------'`------' 
#                 by Nadare\ANiMA     https://github.com/nadaree/SetNameTag

#称号を帰るときの金額を設定(デフォルト: 1000000)
金額: "1000000"

#称号と名前の境となる枠の色を設定します。
left: '['
right: §r]

#ここに禁止にしたいワードを入力してください(Betas)
Bantitle1: OP
Bantitle2: VIP
Bantitle3: 鯖主
