---
# # # # # # # # # # # # # # # # #
#  ____             __ _        #
# / ___|___  _ __  / _(_)  __ _ #
#| |   / _ \| '_ \| |_| | / _` |#
#| |__| (_) | | | |  _| || (_| |#
# \____\___/|_| |_|_| |_| \__, |#
#                         |___/ #
# # # # # # # # # # # # # # # # # by kiu1/nadare

##Title create need money.
金額: "1000000"
##title frame
left: '['
right: §r]
#############



#ここに禁止にしたいワードを入力してください(Betas)
#eng: ban wanna title is write here.
Bantitle1: OP
Bantitle2: VIP
Bantitle3: 鯖主
